### ISSUE TITLE
gamemode does not trigger profile switch

### ISSUE THREAD

**Issue by Mershl** [ilya-zlobintsev/LACT#448]
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

to reproduce:
enable `switch automatically` in LACT
enable `Activate profile when: Gamemode is active` in LACT
open a terminal or two:
`$ watch gamemoded -s`
`$ gamemoderun watch "echo Hello World"`
LACT reports "Selected settings are currently not matched" and no profile switch is seen.

config.yaml
```
version: 1
daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  [...]
profiles:
  Gaming:
    gpus:
      [...]
    rule:
      type: gamemode
      filter: null
current_profile: null
auto_switch_profiles: true
```

Screencast:

[Screencast From 2025-01-15 16-45-58.webm](https://github.com/user-attachments/assets/d9d750a1-ed28-4f78-9ad3-473b96a45e1a)

### System info

```markdown
- LACT version: 0.7.0 (libadwaita)
- GPU model: RX7900XTX
- Kernel version: 6.12.9
- Distribution: Fedora 41 Silverblue
```
