### ISSUE TITLE
7800XT power cap not applying correctly

### ISSUE THREAD

**Issue by positroniumx** [ilya-zlobintsev/LACT#506]
### Checklist

- [x] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [x] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration
- [x] I've checked that the issue still happens in the latest [development build](https://github.com/ilya-zlobintsev/lact?tab=readme-ov-file#development-builds).

### Bug description

I have a strange issue, not sure if LACT or driver related.
Power slider goes to 280W but in testing power averages 250W. Tried various loads, but Kombustor testing shows this issue easily.
So, cat /sys/class/drm/card1/device/hwmon/hwmon5/power1_cap shows 280000000 but doesn't go past 250W average. Now, if I echo "280000000" > /sys/class/drm/card1/device/hwmon/hwmon5/power1_cap , basically the very same value, power consumption instantly jumps to 280W average, and clocks lower a bit.

![Image](https://github.com/user-attachments/assets/d8ca4681-ff9f-437a-b175-f39227606408)

In this photo can be seen where I issued the echo command, on the graph.
Also another issue which might be related to this, if I set constant fan speed and I run the previous echo command, the fan speed reverts to automatic.
cat /sys/class/drm/card1/device/hwmon/hwmon5/power1_cap shows the very same 280000000 value, so theoretically nothing changes as far as this values goes.
If I then drag the power slider in LACT, drag it lower then max it out again at 280 and press apply, the average power consumption again drops to around 250W. This can be seen in the following photo

![Image](https://github.com/user-attachments/assets/80af53f5-8a85-4947-b22b-d8d391057275)
So there is something strange going on which I don't really understand.

edit: forgot to mention that I have -190mV undervolt offset.
Tried with corectrl and when I apply -190mV offset in it it also drops to some 245W draw. power1_cap file still has 280000000 in it. So might be driver related?

### System info

```markdown
- LACT version: r677.6efbad8-1
- GPU model: 7800XT
- Kernel version: 6.13.7
- Distribution: Arch

GPU Model: AMD Radeon RX 7800 XT (0x1002:0x747E:0xC8)
Card Manufacturer: Tul Corporation / PowerColor (0x148C)
Card Model: PowerColor RX 7800 XT Hellhound (0x2427)
Driver Used: amdgpu
VBIOS Version: 022.002.001.021.000001 [2023/08/08 19:59]
VRAM Size: 16368 MiB
GPU Family: GC 11.0.0
ASIC Name: GFX1101/Navi32
Compute Units: 60
VRAM Type: GDDR6
VRAM Manufacturer: samsung
Theoretical VRAM Bandwidth: 623
L1 Cache (Per CU): 32 KiB
L2 Cache: 4096 KiB
L3 Cache: 64 MiB
Resizeable bar: Enabled
CPU Accessible VRAM: 16368
Link Speed: 16.0 GT/s PCIe x16
```

**Comment by ilya-zlobintsev** [comment]
The reason you are seeing this behaviour is that RDNA3 is sensitive to the order the settings are written in, and it is not reliably visible in the sysfs entries if the setting is actually applied or not. So when you write the power limit, it resets the voltage offset (and other clocks settings if you have any)

Could you try manually writing the settings in the following order:
```
echo "280000000" > /sys/class/drm/card1/device/hwmon/hwmon5/power1_cap
echo "vo -190" > /sys/class/drm/card1/device/pp_od_clk_voltage
echo "c" > /sys/class/drm/card1/device/pp_od_clk_voltage
```
(if you have a custom clockspeed too set it with `s 1 2500` for 2500mhz for example before the voltage offset)

**Comment by positroniumx** [comment]
Yeap that seems to work. Those extra 30W can bring anywhere between 4% and 17% more performance depending on test load. Quite nice extra.
But on the heaviest of them I'd like constant fan speed control, how would I set that from command line and where exactly does it need to go in the order?

**Comment by ilya-zlobintsev** [comment]
Could you send your full config from `/etc/lact/config.yaml`, so i can check which exact writes lact generates?

**Comment by positroniumx** [comment]
```
version: 3
daemon:
  log_level: info
  admin_groups:
  - wheel
  - sudo
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  1002:747E-148C:2427-0000:2d:00.0:
    fan_control_enabled: false
    fan_control_settings:
      mode: static
      static_speed: 0.80070084
      temperature_key: edge
      interval_ms: 500
      curve:
        40: 0.35
        50: 0.35
        60: 0.5
        70: 0.75
        80: 1.0
    pmfw_options:
      acoustic_limit: 3000
      acoustic_target: 1100
      minimum_pwm: 35
      target_temperature: 83
      zero_rpm: true
      zero_rpm_threshold: 50
    power_cap: 280.0
    performance_level: auto
    max_core_clock: 3000
    voltage_offset: -190
current_profile: null
auto_switch_profiles: false
```
